<a href="https://colab.research.google.com/github/tejaswini26k/Teju-Google-colab-notebook/blob/main/file_and_numpy_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
product_details=[]
supplier_details=dict()
customer_details=[]
gender={}

fp1=open("Sales.csv","r")
data=fp1.readline()

while(True):

   data=fp1.readline()
   if not data:
       break;
   #print(data)
   #data=data.replace("\n","")
   temp=data.split(",")
   product_details.append(temp[1])
   customer_details.append(temp[3])
   supplier_details.update({temp[0]:temp[2]})
   gender.update({temp[3]:temp[4]})

fp1.close()

customer_details=tuple(customer_details)
print(type(customer_details))


<class 'tuple'>


In [ ]:
print("\nproduct_details\n",product_details,end="")
print("\ncustomer_details\n",customer_details,end="")
print("\nsupplier_details\n",supplier_details,end="")
print("\ngender_details\n",gender,end="")


product_details
 ['Lenovo Laptop', 'Samsung M31', 'Realmi 10pro', 'Oppo F21', 'Lenovo Laptop', 'Samsung M31', '"LG TV 32"""', 'Oppo F21', 'Lenovo Laptop', 'Samsung M31', '"LG TV 32"""', 'Lenovo Laptop', 'Samsung M31', 'Realmi 10pro', 'Lenovo Laptop', 'Oppo F21', '"LG TV 32"""', 'Lenovo Laptop', 'Samsung M31', '"LG TV 32"""']
customer_details
 ('Kaustubh Mahajan', 'Siddhi Kiwale', 'Sanket Kandalkar', 'Yash Mali', 'Yash Bagul', 'Siddhi Kiwale', 'Sanket Kandalkar', 'Kaustubh Mahajan', 'Yash Mali', 'Siddhi Kiwale', 'Sanket Kandalkar', 'Kaustubh Mahajan', 'Yash Mali', 'Siddhi Kiwale', 'Tanuja Mali', 'Kaustubh Mahajan', 'Sanket Kandalkar', 'Siddhi Kiwale', 'Kaustubh Mahajan', 'Yash Mali')
supplier_details
 {'P00001': 'Raka Ele.', 'P00002': 'Vijay Sales', 'P00003': 'Gada Ele.', 'P00004': 'Surya Ele.', 'P00005': 'Raka Ele.', 'P00006': 'Gada Ele.', 'P00007': 'Vijay Sales', 'P00008': 'Surya Ele.', 'P00009': 'Raka Ele.', 'P00010': 'Gada Ele.', 'P00011': 'Surya Ele.', 'P00012': 'Raka Ele.', 'P000

In [ ]:
frequency={}#{lenovo laptop:3}
#iteracting over the list
for item in product_details:
  #checking  the element in dictionary
  if item in frequency:
    #incrementing the counter
    frequency[item]+=1
  else:
      #initialising the count
      frequency[item]=1
#printing the frequency
print(frequency)
newlist=sorted(frequency.items(),key=lambda x:x[1],reverse=True)
sortdict=dict(newlist)
print(sortdict)
print("the most popular product for sales",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"times")

{'Lenovo Laptop': 6, 'Samsung M31': 5, 'Realmi 10pro': 2, 'Oppo F21': 3, '"LG TV 32"""': 4}
{'Lenovo Laptop': 6, 'Samsung M31': 5, '"LG TV 32"""': 4, 'Oppo F21': 3, 'Realmi 10pro': 2}
the most popular product for sales Lenovo Laptop sold 6 times


In [ ]:
frequency={}
#iteracting over the list
for item in supplier_details.values():
  #checking  the element in dictionary
  if item in frequency:
    #incrementing the counter
    frequency[item]+=1
  else:
      #initialising the count
      frequency[item]=1
#printing the frequency
print(frequency)
newlist=sorted(frequency.items(),key=lambda x:x[1],reverse=True)
sortdict=dict(newlist)
print(sortdict)
print("the most popular supplier for sales",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"items")

{'Raka Ele.': 6, 'Vijay Sales': 3, 'Gada Ele.': 5, 'Surya Ele.': 4, 'Deshmukh sales': 2}
{'Raka Ele.': 6, 'Gada Ele.': 5, 'Surya Ele.': 4, 'Vijay Sales': 3, 'Deshmukh sales': 2}
the most popular supplier for sales Raka Ele. sold 6 items


In [ ]:
frequency={}
#iteracting over the list
for item in customer_details:
  #checking  the element in dictionary
  if item in frequency:
    #incrementing the counter
    frequency[item]+=1
  else:
      #initialising the count
      frequency[item]=1
#printing the frequency
print(frequency)
newlist=sorted(frequency.items(),key=lambda x:x[1],reverse=True)
sortdict=dict(newlist)
print(sortdict)
print("the most popular customer for sales",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"items")

NameError: ignored

In [ ]:
frequency={}
#iteracting over the list
for item in gender.values():
  #checking  the element in dictionary
  if item in frequency:
    #incrementing the counter
    frequency[item]+=1
  else:
      #initialising the count
      frequency[item]=1
#printing the frequency
print(frequency)
newlist=sorted(frequency.items(),key=lambda x:x[1],reverse=True)
sortdict=dict(newlist)
print(sortdict)
print("the most popular customer for sales",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"items")

NameError: ignored

In [ ]:
frequency={}
#iteracting over the list
for item in Gender.values():
  #checking  the element in dictionary
  if item in frequency:
    #incrementing the counter
    frequency[item]+=1
  else:
      #initialising the count
      frequency[item]=1
#printing the frequency
print(frequency)
newlist=sorted(frequency.items(),key=lambda x:x[1],reverse=True)
sortdict=dict(newlist)
print(sortdict)
print("the number of customer who are female",list(sortdict.keys())[0],"sold",list(sortdict.values())[0],"times")

NameError: ignored

In [ ]:
#find the number of females customers
#((not to cosider the collection module))

from collections import counter
counter=dict(counter(customer_details))
names=list(counter.keys())
print(names)
male=0
female=0

for name in names:
  if gender[name]=="male\n":
    male=male+1
  if gender[name]=="female\n":
    female+=1
print("total no. of male=",male)
print("toatal no. of female=",female)

ImportError: ignored

In [ ]:
import numpy as np

In [ ]:
array1=np.array([[3,4,5],[5,6,8],[6,9,9]])
array1

array([[3, 4, 5],
       [5, 6, 8],
       [6, 9, 9]])

In [ ]:
array2=np.array([[12,34,45],[32,34,67],[12,31,42]])
array2

array([[12, 34, 45],
       [32, 34, 67],
       [12, 31, 42]])

In [ ]:
array1+array2

array([[15, 38, 50],
       [37, 40, 75],
       [18, 40, 51]])

In [ ]:
array2-array1

array([[ 9, 30, 40],
       [27, 28, 59],
       [ 6, 22, 33]])

In [ ]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[0, 1, 2])

6


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=a*b
print(c)

[ 2  6 12]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=a/b
print(c)

[0.5        0.66666667 0.75      ]


In [ ]:
import numpy as np
a=np.array([1,2,3])
mean_a=np.mean(a)
print(mean_a)

2.0


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


In [ ]:
b[2]=4
print(a)
print(b)

[1 2 3]
[1 2 4]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=a.view()
b[1]=5
print(a)
print(b)

[1 5 3]
[1 5 3]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.hstack((a,b))
print(c)

[1 2 3 2 3 4]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.vstack((a,b))
print(c)

[[1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.column_stack((a,b))
print(c)

[[1 2]
 [2 3]
 [3 4]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.row_stack((a,b))
print(c)

[[1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
a=np.array([3,2,0,1])
print(np.sort(a))

[0 1 2 3]


In [ ]:
import numpy as np
a=np.array([[3,2,0],[3,4,5]])
print(np.sort(a))

[[0 2 3]
 [3 4 5]]


In [ ]:
import numpy as np
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.stack((a,b),axis=0)
print(c)

[[1 2 3]
 [2 3 4]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.stack((a,b),axis=1)
print(c)

[[1 2]
 [2 3]
 [3 4]]


In [ ]:
import numpy as np
mx=np.array([[5,10],[15,20]])
print("matrix=\n",mx)
print("\nthe summation of elements=")
print(np.sum(mx))
print("\nthe column wise summation=")
print(np.sum(mx,axis=0))
print("\nthe row wise summation=")
print(np.sum(mx,axis=1))

matrix=
 [[ 5 10]
 [15 20]]

the summation of elements=
50

the column wise summation=
[20 30]

the row wise summation=
[15 35]


In [ ]:
import numpy as np
mx=np.array([[5,10],[15,20]])
print("matrix=\n",mx)
print("\nthe transpose")
print(mx.T)

matrix=
 [[ 5 10]
 [15 20]]

the transpose
[[ 5 15]
 [10 20]]


In [ ]:
import numpy as np
a=np.arange(20)
print("\n array is:\n",a)
print("\n a[-8:17:1]=",a[-8:17:1])
print("\n a[10:]=",a[10:])


 array is:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 a[-8:17:1]= [12 13 14 15 16]

 a[10:]= [10 11 12 13 14 15 16 17 18 19]


In [ ]:
import numpy as np
list1=[x for x in range(0,101,2)]
a=np.array(list1)
print(a)
print(type(list1))
print(type(a))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
b=np.arange(50,0,-1).reshape(10,5)
print(b)

[[50 49 48 47 46]
 [45 44 43 42 41]
 [40 39 38 37 36]
 [35 34 33 32 31]
 [30 29 28 27 26]
 [25 24 23 22 21]
 [20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [ ]:
b=np.arange(9,0,-1).reshape(3,3)
print(b)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
nparray=np.empty((3,3),int)
nparray

array([[           72140096,                   0, 7594318452449042464],
       [ 754755775995343725, 2314885530818453536, 8028075836850796645],
       [2336361506924426094, 7310302487399916898,                 160]])

In [ ]:
z=np.linspace(0,100,5)
print(z)

[  0.  25.  50.  75. 100.]


In [ ]:
a=np.array([1,3,2,4,5])
b=np.array([1,2,3,4,5])
print(np.where(a==b))


(array([0, 3, 4]),)


In [ ]:
import numpy as np
arr=np.array([10,20,30,4,50,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
import numpy as np
arr=np.array([10,20,33,45,58,68,74,89])
x=np.where(arr%2==0)
print(x)

(array([0, 1, 4, 5, 6]),)


In [ ]:
import numpy as np
arr=np.array([10,20,33,45,58,68,74,89])
x=np.where(arr%2!=0)
print(x)

(array([2, 3, 7]),)


In [ ]:
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


In [ ]:
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,9)
print(x)

3


In [ ]:
import numpy as np
arr=np.array([61,73,83,91])
x=np.searchsorted(arr,73)
print(x)

1


In [ ]:
import numpy as np
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7,side='right')
print(x)

2


In [ ]:
import numpy as np
arr=np.array([10,20,40,60])
x=np.searchsorted(arr,[20,40,60])
print(arr)
print(x)

[10 20 40 60]
[1 2 3]


In [ ]:
array1=np.array([1,2,3,4,5,9,6,7,8,9,9])
print(np.std(array1))
print(np.min(array1))
print(np.sum(array1))
print(np.median(array1))
print(np.mean(array1))
from scipy import stats
print("most frequent element=",stats.mode(array1)[0])
print("number of occurences=",stats.mode(array1)[1])
print(np.var(array1))

2.7990553306073913
1
63
6.0
5.7272727272727275
most frequent element= [9]
number of occurences= [3]
7.834710743801653


<ipython-input-70-a66fcc71840e>:8: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("most frequent element=",stats.mode(array1)[0])
<ipython-input-70-a66fcc71840e>:9: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("number of occurences=",stats.mode(array1)

In [ ]:
array1=np.array([1,2,3,12,5,7,0])
print(np.count_nonzero(array1))
print(np.nonzero(array1))
print(array1.size)

6
(array([0, 1, 2, 3, 4, 5]),)
7


In [ ]:
https://numpy.org/doc/1.20/user/theory.broadcasting.html

In [ ]:
https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm

SyntaxError: ignored

In [ ]:
import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print ('First array:')
print (a)
print ('\n')

print ('Second array:')
print (b)
print ('\n')

print ('First Array + Second Array')
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [ ]:
import numpy as np

a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
print (c)

[ 10  40  90 160]


In [ ]:
product_details=[]
supplier_details=dict()
customer_details=[]
gender={}

fp1=open("Sales.csv","r")
data=fp1.readline()

while(True):

   data=fp1.readline()
   if not data:
       break;
   #print(data)
   #data=data.replace("\n","")
   temp=data.split(",")
   product_details.append(temp[1])
   customer_details.append(temp[3])
   supplier_details.update({temp[0]:temp[2]})
   gender.update({temp[3]:temp[4]})

fp1.close()

customer_details=tuple(customer_details)
print(type(customer_details))

<class 'tuple'>


In [ ]:
product_dtails=[]
supplier_details=[]
customer_details=[]
gender=[]
import numpy as np
list1=[x for x in range(product_details)]
a=np.array(list1)
print(a)
print(type(list1))
print(type(a))

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
https://www.w3resource.com/numpy/array-creation/loadtxt.php

In [ ]:
import numpy as np
array3=np.loadtxt('/content/fees.csv',delimiter=',',dtype=str,skiprows=1)
print(array3)
roll_number=[]
number_of_courses=[]
fees=[]
division=[]
for i in array3:
  roll_number.append(int(i[0]))
  number_of_courses.append(int(i[1]))
  fees.append(int(i[2]))
  division.append((i[3]))
print(roll_number)
print(number_of_courses)
print(fees)
print(division)
arr_roll_number=np.array(roll_number)
arr_number_of_courses=np.array(number_of_courses)
arr_fees=np.array(fees)
arr_division=np.array(division)

print('array1:',arr_roll_number)
print('array2:',arr_number_of_courses)
print('array3:',arr_fees)
print('array4:',arr_division)

[['101' '1' '500' 'A' '']
 ['102' '1' '500' 'A' '']
 ['103' '8' '4000' 'A' '']
 ['104' '1' '500' 'B' '']
 ['105' '1' '500' 'B' '']
 ['106' '2' '1000' 'C' '']
 ['109' '2' '1000' 'C' '']
 ['110' '1' '500' 'A' '']
 ['111' '3' '1500' 'B' '']
 ['114' '2' '1000' 'C' '']
 ['115' '2' '1000' 'D' '']
 ['117' '6' '3000' 'G' '']
 ['119' '3' '1500' 'G' '']
 ['120' '2' '1000' 'H' '']
 ['121' '1' '500' 'H' '']
 ['122' '2' '1000' 'E' '']
 ['123' '2' '1000' 'E' '']
 ['125' '3' '1500' 'E' '']
 ['126' '4' '2000' 'C' '']
 ['127' '1' '500' 'F' '']
 ['128' '1' '500' 'F' '']
 ['129' '6' '3000' 'E' '']
 ['130' '2' '1000' 'G' '']
 ['131' '3' '1500' 'G' '']]
[101, 102, 103, 104, 105, 106, 109, 110, 111, 114, 115, 117, 119, 120, 121, 122, 123, 125, 126, 127, 128, 129, 130, 131]
[1, 1, 8, 1, 1, 2, 2, 1, 3, 2, 2, 6, 3, 2, 1, 2, 2, 3, 4, 1, 1, 6, 2, 3]
[500, 500, 4000, 500, 500, 1000, 1000, 500, 1500, 1000, 1000, 3000, 1500, 1000, 500, 1000, 1000, 1500, 2000, 500, 500, 3000, 1000, 1500]
['A', 'A', 'A', 'B', 'B', 'C

In [ ]:
print(np.min(arr_fees))
print(np.max(arr_fees))
print(np.sum(arr_fees))
print(np.sum(arr_fees/len(arr_fees)))

500
4000
30000
1250.0


In [ ]:
arr_number_of_courses*arr_fees


array([  500,   500, 32000,   500,   500,  2000,  2000,   500,  4500,
        2000,  2000, 18000,  4500,  2000,   500,  2000,  2000,  4500,
        8000,   500,   500, 18000,  2000,  4500])

In [ ]:
arr_number_of_courses+arr_fees

array([ 501,  501, 4008,  501,  501, 1002, 1002,  501, 1503, 1002, 1002,
       3006, 1503, 1002,  501, 1002, 1002, 1503, 2004,  501,  501, 3006,
       1002, 1503])

In [ ]:
arr_fees-arr_number_of_courses

array([ 499,  499, 3992,  499,  499,  998,  998,  499, 1497,  998,  998,
       2994, 1497,  998,  499,  998,  998, 1497, 1996,  499,  499, 2994,
        998, 1497])

In [ ]:
arr_fees/arr_number_of_courses

array([500., 500., 500., 500., 500., 500., 500., 500., 500., 500., 500.,
       500., 500., 500., 500., 500., 500., 500., 500., 500., 500., 500.,
       500., 500.])

In [ ]:
mx=np.array([arr_fees,arr_number_of_courses])
print("matrix=\n",mx)
print("\nthe transpose")
print(mx.T)

matrix=
 [array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19])
 array([1, 1, 8, 1, 1, 2, 2, 1, 3, 2, 2, 6, 3, 2, 1, 2, 2, 3, 4, 1, 1, 6,
        2, 3])                                                           ]

the transpose
[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19])
 array([1, 1, 8, 1, 1, 2, 2, 1, 3, 2, 2, 6, 3, 2, 1, 2, 2, 3, 4, 1, 1, 6,
        2, 3])                                                           ]


<ipython-input-34-5efeeaaafc50>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  mx=np.array([arr_fees,arr_number_of_courses])


In [ ]:
print(arr_number_of_courses[1:5])
print(arr_fees[1:6])
print(arr_roll_number[1:6])


[1 8 1 1]
[ 500 4000  500  500 1000]
[102 103 104 105 106]


In [ ]:
mean_a=np.mean(arr_fees)
print(mean_a)



1250.0


In [ ]:
median_a=np.median(arr_fees)
print(median_a)
std_a=np.std(arr_fees)
print(std_a)

1000.0
901.3878188659974


In [ ]:
arr1=np.bitwise_or(arr_roll_number,arr_fees)
print(arr1)
arr2=np.bitwise_and(arr_roll_number,arr_fees)
print(arr2)
arr3=np.bitwise_xor(arr_roll_number,arr_fees)
print(arr3)
arr4=np.bitwise_not(arr_number_of_courses)
print(arr4)

[ 501  502 4071  508  509 1002 1005  510 1535 1018 1019 3069 1535 1016
  509 1018 1019 1533 2046  511  500 3001 1002 1503]
[100 100  32  96  96 104 104 100  76  96  96  48  84 104 112 104 104  92
  80 116 128 128 128 128]
[ 401  402 4039  412  413  898  901  410 1459  922  923 3021 1451  912
  397  914  915 1441 1966  395  372 2873  874 1375]
[-2 -2 -9 -2 -2 -3 -3 -2 -4 -3 -3 -7 -4 -3 -2 -3 -3 -4 -5 -2 -2 -7 -3 -4]


In [ ]:

arr_roll_number.view()


array([101, 102, 103, 104, 105, 106, 109, 110, 111, 114, 115, 117, 119,
       120, 121, 122, 123, 125, 126, 127, 128, 129, 130, 131])

In [ ]:
arr=arr_number_of_courses.copy()
print(arr)

[1 1 8 1 1 2 2 1 3 2 2 6 3 2 1 2 2 3 4 1 1 6 2 3]


In [ ]:
arr3=np.vstack((arr_number_of_courses,arr_fees))
print(arr3)
arr4=np.hstack((arr_number_of_courses,arr_fees))
print(arr4)
arr3=np.vstack((arr_number_of_courses,arr_roll_number))
print(arr3)
arr4=np.hstack((arr_number_of_courses,arr_roll_number))
print(arr4)

[[   1    1    8    1    1    2    2    1    3    2    2    6    3    2
     1    2    2    3    4    1    1    6    2    3]
 [ 500  500 4000  500  500 1000 1000  500 1500 1000 1000 3000 1500 1000
   500 1000 1000 1500 2000  500  500 3000 1000 1500]]
[   1    1    8    1    1    2    2    1    3    2    2    6    3    2
    1    2    2    3    4    1    1    6    2    3  500  500 4000  500
  500 1000 1000  500 1500 1000 1000 3000 1500 1000  500 1000 1000 1500
 2000  500  500 3000 1000 1500]
[[  1   1   8   1   1   2   2   1   3   2   2   6   3   2   1   2   2   3
    4   1   1   6   2   3]
 [101 102 103 104 105 106 109 110 111 114 115 117 119 120 121 122 123 125
  126 127 128 129 130 131]]
[  1   1   8   1   1   2   2   1   3   2   2   6   3   2   1   2   2   3
   4   1   1   6   2   3 101 102 103 104 105 106 109 110 111 114 115 117
 119 120 121 122 123 125 126 127 128 129 130 131]


In [ ]:
arr5=np.array(arr_fees)
print(np.sort(arr5))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(np.sort(arr_fees))
print(np.sort(roll_number))
print(np.sort(number_of_courses))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[101 102 103 104 105 106 109 110 111 114 115 117 119 120 121 122 123 125
 126 127 128 129 130 131]
[1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 3 3 3 3 4 6 6 8]


In [ ]:
arr_fees=np.arange(20)
print("\n array is:",arr_fees)
print("\n arr_fees[-8:17:1]=",arr_fees[-8:17:1])
print("\n arr_fees[10:]=",arr_fees[10:])


 array is: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

 arr_fees[-8:17:1]= [12 13 14 15 16]

 arr_fees[10:]= [10 11 12 13 14 15 16 17 18 19]


In [ ]:
indices = np.arange(len(arr_number_of_courses))
for i in indices:
    print("number of courses at index", i, ":", arr_number_of_courses[i])

number of courses at index 0 : 1
number of courses at index 1 : 1
number of courses at index 2 : 8
number of courses at index 3 : 1
number of courses at index 4 : 1
number of courses at index 5 : 2
number of courses at index 6 : 2
number of courses at index 7 : 1
number of courses at index 8 : 3
number of courses at index 9 : 2
number of courses at index 10 : 2
number of courses at index 11 : 6
number of courses at index 12 : 3
number of courses at index 13 : 2
number of courses at index 14 : 1
number of courses at index 15 : 2
number of courses at index 16 : 2
number of courses at index 17 : 3
number of courses at index 18 : 4
number of courses at index 19 : 1
number of courses at index 20 : 1
number of courses at index 21 : 6
number of courses at index 22 : 2
number of courses at index 23 : 3


In [ ]:
import numpy as np
np.count_nonzero(arr_fees==4000)




1

In [ ]:
np.count_nonzero(arr_fees==500)

8

In [ ]:
np.count_nonzero(arr_fees<1500)

16

In [ ]:
a=arr_fees[1:5]
print(a)
b=arr_number_of_courses[1:5]
print(b)
c=a+b
print(c)

[ 500 4000  500  500]
[1 8 1 1]
[ 501 4008  501  501]


SyntaxError: ignored

In [ ]:
import pandas as pd
mydataset={
    'batch':["c1","c2","c3","c4"],
    'strength':[21,19,21,23]
}
df=pd.DataFrame(mydataset)
print(df)

  batch  strength
0    c1        21
1    c2        19
2    c3        21
3    c4        23


In [ ]:
import pandas as pd
result={"sic":55,"am":60,"eds":66}
sr=pd.Series(result)
print(sr)


sic    55
am     60
eds    66
dtype: int64


In [ ]:
import pandas as pd
result={"sic":55,"am":60,"eds":66}
sr=pd.Series(result,index=["sic","eds"])
print(sr)

sic    55
eds    66
dtype: int64


In [ ]:
import pandas as pd
a=[10,70,20]
myvar=pd.Series(a)
print(myvar)

0    10
1    70
2    20
dtype: int64
